### ISSUE TITLE
VM action fails if artifacts already exists

### ISSUE THREAD

**Issue by edburns** [microsoft/microsoft-partner-center-github-action#10]
Hello @zhengchang907,

We tried to use the action for the first time today since the initial publish, but it failed with this error, as you can see at [this run](https://github.com/WASdev/azure.websphere-traditional.image/actions/runs/4833000001/jobs/8612482588). For your convenience, here is the error.

```bash
***
  "$schema": "https://schema.mp.microsoft.com/schema/configure-status/2022-07-01",
  "jobId": "0abfafad-2223-49b8-b8e2-7acfebc28b9f",
  "jobStatus": "completed",
  "jobResult": "failed",
  "jobStart": "2023-04-28T17:52:02.1242996Z",
  "jobEnd": "2023-04-28T17:52:04.1312745Z",
  "errors": [
    ***
      "code": "badRequest",
      "message": "Cannot delete image '9.0.20230404' of type 'X64Gen1' as it is already published.",
      "details": [
        ***
          "code": "invalidResource",
          "message": "Failure for resource: virtual-machine-plan-technical-configuration-0, schema: virtual-machine-plan-technical-configuration"
        ***
      ]
    ***
  ]
***
Error happens when processing job
```

I am guessing the failure has something to do with this [line](https://github.com/microsoft/microsoft-partner-center-github-action/blob/4a6b1e821cef19e5bd3aaa3bcd4b92fedd048fe0/entrypoint.sh#L355).

Can you please push a PR that resolves this problem so we can use it on [tWAS](https://github.com/WASdev/azure.websphere-traditional.image)?  In the meantime I am going to revert to the pre-automatic publishing status of the workflows.

**Comment by zhengchang907** [comment]
Hi @edburns , 

The GitHub action will try to delete configurations that are not in state "deprecated" at [entrypoint.sh#L355](https://github.com/microsoft/microsoft-partner-center-github-action/blob/main/entrypoint.sh#L355) because in the test offer "generallyAvailable" configurations are drafts. 

I think we need to update this line to `imageVersionsFiltered=$(echo ${imageVersions} | jq -r 'map(if .lifecycleState == "generallyAvailable" then .lifecycleState = "deleted" else . end)')`. My guess in **"real offers"** some published VM configurations' lifecycle states are neither "generallyAvailable" nor "deprecated"(see schema below), so they cannot be marked as "deleted".

According to [schema](https://product-ingestion.azureedge.net/schema/virtual-machine-plan-technical-configuration/2022-03-01-preview3): **"deleted only if in draft and never published. Deprecated replaces StopSold"**.
```
...
  "$defs": {
    "https://product-ingestion.azureedge.net/schema/resource-lifecycle-state/2022-03-01-preview2": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "$id": "https://product-ingestion.azureedge.net/schema/resource-lifecycle-state/2022-03-01-preview2",
      "type": "string",
      "$comment": "deleted only if in draft and never published. Deprecated replaces StopSold",
      "enum": [
        "notAvailable",
        "neverUsed",
        "test",
        "preview",
        "generallyAvailable",
        "deprecated",
        "decommissioned",
        "deleted"
      ]
    },
...
```
Only three lifecycle states can be configured for VM image, that is the reason I tried to deleted the "generallyAvailable" ones because they should be the drafts. 
```
...
"vmImageVersion": {
      "type": "object",
      "properties": {
        "versionNumber": {
          "type": "string",
          "minLength": 1,
          "maxLength": 32,
          "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$"
        },
        "vmImages": {
          "type": "array",
          "minItems": 1,
          "maxItems": 2,
          "items": {
            "$ref": "#/$defs/vmImage"
          }
        },
        "lifecycleState": {
          "$ref": "https://product-ingestion.azureedge.net/schema/resource-lifecycle-state/2022-03-01-preview2",
          "default": "generallyAvailable",
          "enum": [
            "generallyAvailable",
            "deprecated",
            "deleted"
          ]
        },
        "deprecationSchedule": {
          "$ref": "https://product-ingestion.azureedge.net/schema/deprecation-schedule/2022-03-01-preview2"
        }
      },
...
```

**Comment by majguo** [comment]
Thank you @zhengchang907 for your quick fix! The fix looks good to me, I just merged your PR. Cc @edburns.
